### ISSUE TITLE
Error: designator order for field '_lv_font_t::static_bitmap'

### ISSUE THREAD

**Issue by francisperea** [lvgl/lv_font_conv#142]
Hi all, 

I need a font with accented chars for Spanish language. After reading the docs I see the only way is to create my own font.

I have tried both the online converter and the self installed version and both give me the same error when trying to compile with LVGL 9.3.0:

`designator order for field '_lv_font_t::static_bitmap'  does not match declaration order in 'const lv_font_t' {aka 'const _lv_font_t'}`

Any help? Is it me or is there any issue with the code?

I've tried to compile both under Arduino IDE and with VSC + esptools

**Comment by francisperea** [comment]
I've got some help in the forums and I could make it compile by just commenting then line inside this define:

```
#if LV_VERSION_CHECK(9, 3, 0)
//    .static_bitmap = 1,        /*Bitmaps are stored as const so they are always static */
#endif
```

In case it should be corrected for next release.

**Comment by kisvegabor** [comment]
Hi,

Can you test with these changes? https://github.com/lvgl/lv_font_conv/pull/145

Just move `.static_bitmap` above  `underline_position`.

**Comment by francisperea** [comment]
Hi @kisvegabor, 

Thanks for your help.

I just tested the online converter and still got the error:

Compilation error: designator order for field '_lv_font_t::static_bitmap' does not match declaration order in 'const lv_font_t' {aka 'const _lv_font_t'}

If I comment line 669 of attached file it compiles without errors:

.static_bitmap = 0,

Should I also try the offline version?

[roboto.h.txt](https://github.com/user-attachments/files/22613896/roboto.h.txt)

**Comment by mlc42** [comment]
today i create a font with the online converter for lvgl 8.4  and have the same issue.  
chatgpt say there is no .static_bitmap above lvgl 7.  I removed the line
and the font is working.

**Comment by boschatz** [comment]
#145 Fixed the issue for me.
